name: myapp

services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - '3000:3000'
    volumes:
      - ./src:/src/app
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
